spring:
  cloud:
    consul:
      discovery:
        enabled: true
        tags: http
        port: ${server.port}
        metadata:
          keyType: ${app.key.type}
        instance-id: "${spring.application.name}"
        management-port: ${management.server.port}
      config:
        enabled: true
        format: YAML
        data-key: data