logging:
  level:
    root: INFO
  #    io.rsocket.FrameLogger: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %logger.%M - %msg%n"

management:
  info:
    git:
      mode: full
  endpoint:
    shutdown:
      enabled: true
    enabled-by-default: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,shutdown,rootkeys

spring:
  main:
    web-application-type: reactive
  application:
    name: "${app.primary}-service-${app.proto}"