app:
  client:
    discovery:
      config:
        pubsub:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: pubsub.
        index:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: index.
        persistence:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: persist.
        key:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: key.
        message:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: message.
        secrets:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: secrets.
        topic:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: topic.
        user:
          dest: "${CORE_HOST:127.0.0.1}:${CORE_PORT:6790}"
          prefix: user.
