spring:
  cloud:
    consul:
      discovery:
        enabled: true
        default-query-tag: rsocket

app:
  client:
    discovery:
      config:
        pubsub:
          dest: core-service-rsocket
          prefix: pubsub.
        index:
          dest: core-service-rsocket
          prefix: index.
        persistence:
          dest: core-service-rsocket
          prefix: persist.
        key:
          dest: core-service-rsocket
          prefix: key.
        message:
          dest: core-service-rsocket
          prefix: message.
        topic:
          dest: core-service-rsocket
          prefix: topic.
        user:
          dest: core-service-rsocket
          prefix: user.
        secrets:
          dest: core-service-rsocket
          prefix: secrets.