app:
  oauth2:
    jwk:
      path: file:/etc/keys/server_keycert.jwk
    entrypoint-path: /login
    client:
      id: chat-client
      key: 31649af5-0154-4be5-8695-fda9d18b7981
      secret: "{noop}secret"
      redirect-uris:
        - http://127.0.0.1:8080/login/oauth2/code/chat-client-oidc
        - http://127.0.0.1:8080/authorized
      redirect-uri-prefix: http://127.0.0.1:8080
      additional-scopes:
        - openid
        - profile