spring:
  cloud:
    consul:
      discovery:
        tags: ${app.server.proto}
        port: ${server.port}
        metadata:
          keyType: ${app.key.type}
        instance-id: "${spring.application.name}"
        management-port: ${management.server.port}