# Don't forget, the roles must specify a valid or wildcard role mapped to the wildcard user (anonymous)
app:
  init:
    passwordEncoder: bcrypt
    initialRoles:
      rolesAllowed: [ "READ", "CREATE", "WRITE", "REMOVE", "SEND", "JOIN", "*" ]
      wildcard: "*"
      roles:
        - { user: Admin, target: Admin, role: "*" }
        - { user: Anon, target: User, role: FIND }
        - { user: Anon, target: User, role: NEW }
        - { user: Anon, target: Message, role: GET }
        - { user: User, target: Message, role: SEND }
        - { user: User, target: MessageTopic, role: ALL }
        - { user: User, target: MessageTopic, role: GET }
        - { user: User, target: MessageTopic, role: JOIN }
        - { user: User, target: MessageTopic, role: MEMBERS }
    initialUsers:
      Anon:
        handle: Anon
        name: "ANY USER"
        imageUri: chatimg://anon.png
        password: _
      Admin:
        handle: Admin
        name: "SUPER USER"
        imageUri: chatimg://plaid.png
        password: changeme