apiVersion: v1
kind: Pod
metadata:
  name: temp-cert-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - sleep 3600
      volumeMounts:
        - name: chat-certs
          mountPath: /etc/keys
  restartPolicy: OnFailure
  volumes:
    - name: chat-certs
      persistentVolumeClaim:
        claimName: demo-chat-server-keys-pvc