apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-chat-server-keys-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi