package com.demo.chat.test.rsocket

import com.demo.chat.convert.JsonNodeToAnyConverter
import com.demo.chat.domain.serializers.JacksonModules
import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.ImportAutoConfiguration
import org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration
import org.springframework.boot.rsocket.autoconfigure.RSocketMessagingAutoConfiguration
import org.springframework.boot.rsocket.autoconfigure.RSocketRequesterAutoConfiguration
import org.springframework.boot.rsocket.autoconfigure.RSocketServerAutoConfiguration
import org.springframework.boot.rsocket.autoconfigure.RSocketStrategiesAutoConfiguration
import org.springframework.context.annotation.ComponentScan

class TestModules : JacksonModules(JsonNodeToAnyConverter, JsonNodeToAnyConverter)

@SpringBootConfiguration
@EnableAutoConfiguration
@ComponentScan
@ImportAutoConfiguration(TestModules::class)
class RSocketServerTestConfiguration