dist: trusty
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - redis-tools
      - redis-server
language: java
jdk: oraclejdk8
services:
  - redis-server
before_script:
  - export REDIS_TEST_PATH=`which redis-server`