#!/usr/bin/env bash
# check-types.sh — run pyright with the resolved Python path.
# Generated by generate-env-lsp.sh.
# Usage: ./check-types.sh [pyright args...]
#   ./check-types.sh                       # check whole project
#   ./check-types.sh path/to/file.py       # check one file
#   ./check-types.sh --outputjson . | jq   # JSON output
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
[ -f "$SCRIPT_DIR/env.custom" ] && source "$SCRIPT_DIR/env.custom"
source "$SCRIPT_DIR/env.lsp"

exec pyright --pythonpath "$LSP_PYTHON" "$@"
