#!/usr/bin/env bash
# start-lsp.sh — verify LSP prerequisites and start the MCP bridge daemon.
# Generated by generate-env-lsp.sh. Re-run generator to update.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
[ -f "$SCRIPT_DIR/env.custom" ] && source "$SCRIPT_DIR/env.custom"

if [ ! -f "$SCRIPT_DIR/env.lsp" ]; then
    echo "env.lsp not found. Run: ./generate-env-lsp.sh"
    exit 1
fi
source "$SCRIPT_DIR/env.lsp"

echo "Checking prerequisites..."
fail=0
for bin in "$LSP_PYRIGHT_BIN" "$LSP_TSS_BIN" "$LSP_PYTHON"; do
    if [ -z "$bin" ] || [ ! -x "$bin" ]; then
        echo "  MISSING  $bin  (re-run ./generate-env-lsp.sh)"
        fail=1
    else
        echo "  ok       $bin"
    fi
done
[ "$fail" -ne 0 ] && exit 1

echo ""
echo "Environment:"
echo "  workspace   $LSP_WORKSPACE"
echo "  port        $LSP_PORT"
echo "  log         $LSP_LOG"
echo "  pid         $LSP_PID"

if [ -f "$LSP_PID" ]; then
    pid=$(cat "$LSP_PID")
    if kill -0 "$pid" 2>/dev/null; then
        echo "LSP bridge already running (pid $pid). Use stop-lsp.sh to restart."
        exit 0
    else
        echo "(Stale PID file removed)"
        rm "$LSP_PID"
    fi
fi

if ! BRIDGE=$(command -v lsp-mcp-bridge 2>/dev/null); then
    echo "Error: lsp-mcp-bridge not found on PATH."
    echo "  Install it with:  just install   (from the lsp-mcp-bridge source directory)"
    echo "  Or manually:      cp /path/to/lsp-mcp-bridge ~/.local/bin/"
    exit 1
fi
mkdir -p "$(dirname "$LSP_LOG")"
nohup "$BRIDGE" \
    --workspace "$LSP_WORKSPACE" \
    --port      "$LSP_PORT"      \
    --env-lsp   "$SCRIPT_DIR/env.lsp" \
    >> "$LSP_LOG" 2>&1 &
echo $! > "$LSP_PID"
echo "Started (pid $(cat "$LSP_PID")) → http://localhost:$LSP_PORT/mcp"
