#!/usr/bin/env bash
# stop-lsp.sh — stop the LSP MCP bridge daemon.
# Generated by generate-env-lsp.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
[ -f "$SCRIPT_DIR/env.custom" ] && source "$SCRIPT_DIR/env.custom"

if [ ! -f "$SCRIPT_DIR/env.lsp" ]; then
    echo "env.lsp not found. Run: ./generate-env-lsp.sh"
    exit 1
fi
source "$SCRIPT_DIR/env.lsp"

if [ ! -f "$LSP_PID" ]; then
    echo "LSP bridge not running (no PID file at $LSP_PID)"
    exit 0
fi

pid=$(cat "$LSP_PID")
if kill -0 "$pid" 2>/dev/null; then
    kill "$pid"
    rm "$LSP_PID"
    echo "Stopped LSP bridge (pid $pid)"
else
    rm "$LSP_PID"
    echo "PID file was stale (pid $pid already gone), removed"
fi
