logging:
  level:
    root: INFO
  #    io.rsocket.FrameLogger: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %logger.%M - %msg%n"

management:
  info:
    git:
      mode: full
  endpoint:
    shutdown:
      enabled: true
    enabled-by-default: true
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,shutdown,rootkeys

spring:
  main:
    web-application-type: reactive
  application:
    name: "${app.primary}-service-${app.proto}"
  cloud:
    consul:
      discovery:
        enabled: true
        tags: ${app.proto}
        port: ${spring.rsocket.server.port}
        metadata:
          rsocketPort: ${spring.rsocket.server.port}
          keyType: ${app.key.type}
        instance-id: "${spring.application.name}:${random.value}"
        management-port: ${management.server.port}
      config:
        enabled: true
        format: YAML
        data-key: data