apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-chat-server-keys
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /etc/keys