app:
  service:
    core:
      # redis-pubsub -> TopicPubSubServiceRedis (Redis Pub/Sub, non-durable)
      # redis-stream -> TopicPubSubTopicInventoryRedisStream (Redis Streams, durable)
      pubsub: redis-pubsub
