apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-chat
  name: demo-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-chat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-chat
    spec:
      volumes:
        - name: chat-certs
          secret:
            secretName: chat-server-keystore
      containers:
      - image: localhost:5001/memory-core-service-rsocket:0.0.2
        name: memory-core-service-rsocket
        resources: {}
        volumeMounts:
        - name: chat-certs
          mountPath: /etc/keys
          readOnly: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-chat
  name: demo-chat
spec:
  ports:
  - name: 6790-6790
    port: 6790
    protocol: TCP
    targetPort: 6790
  - name: 6791-6791
    port: 6791
    protocol: TCP
    targetPort: 6791
  - name: 6792-6792
    port: 6792
    protocol: TCP
    targetPort: 6792
  selector:
    app: demo-chat
  type: ClusterIP
status:
  loadBalancer: {}
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: demo-chat
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      nodePort: 6791
#      port: 6791
#  selector:
#    app: demo-chat
#status:
#  loadBalancer: {}