logging:
  level:
    root: info

spring:
  main:
    web-application-type: none
  application:
    name: test-client
  cloud:
    consul:
      service-registry:
        enabled: true
      enabled: true
      discovery:
        enabled: true
        instance-id: foobar123
    discovery:
      reactive:
        enabled: true

management:
  endpoints:
    enabled-by-default: false


app:
  rsocket:
    client:
      config:
        pubsub:
          dest: core-service-rsocket
          prefix: pubsub.
        index:
          dest: core-service-rsocket
          prefix: index.
        persistence:
          dest: core-service-rsocket
          prefix: persist.
        key:
          dest: core-service-rsocket
          prefix: key.
        message:
          dest: core-service-rsocket
          prefix: message.
        topic:
          dest: core-service-rsocket
          prefix: topic.
        user:
          dest: core-service-rsocket
          prefix: user.
        secrets:
          dest: core-service-rsocket
          prefix: secrets.