apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-chat
  name: demo-chat
spec:
  ports:
  - name: rsocket
    port: 6790
    protocol: TCP
    targetPort: 6790
  - name: actuator
    port: 6791
    protocol: TCP
    targetPort: 6791
  - name: websocket
    port: 6792
    protocol: TCP
    targetPort: 6792
  selector:
    app: demo-chat
  type: ClusterIP
status:
  loadBalancer: {}
