export CORE_PORT=${CORE_PORT:=6790}
export CORE_RSOCKET_PORT=$((CORE_PORT))
export CORE_MGMT_PORT=${CORE_MGMT_PORT:=$((CORE_PORT+1))}
export CONSUL_HOST=${CONSUL_HOST:="127.0.0.1"}
export CONSUL_PORT=${CONSUL_PORT:=8500}
export DEBUG_PORT=9060

export AUTHSERV_HTTP_PORT=${AUTHSERV_HTTP_PORT:=9000}
export AUTHSERV_MGMT_PORT=${AUTHSERV_MGMT_PORT:=9001}

export HTTP_PORT=$((CORE_PORT+2))
export HTTP_MGMT_PORT=$((HTTP_PORT+1))

export GATEWAY_HTTP_MGMT_PORT=8080
export GATEWAY_HTTP_PORT=80

export SHELL_MGMT_PORT=9101