version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: authserver
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d   # Mount the local sql_scripts directory

volumes:
  db_data: