server:
  port: 8080
spring:
  application:
    name: chat-authorization-server
  main:
    web-application-type: servlet
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false
        format: YAML
        data-key: data