spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserver
    username: ${app.authserv.jdbc.user}
    password: ${app.authserv.jdbc.pass}
    driver-class-name: org.postgresql.Driver
  application:
    name: chat-authorization-server
  main:
    web-application-type: servlet
  security:
    oauth2:
      authorizationserver:
        client:
          chatclient:
            registration:
              clientId:
              client-secret:
              client-authentication-method:
              authorization-grant-types:
              redirectUris:
              scopes:
            requireAuthorizationConcent: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
