spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserver
    driver-class-name: org.postgresql.Driver
  application:
    name: chat-authorization-server
  main:
    web-application-type: servlet
  security:
    oauth2:
      authorizationserver:
        client:
          chatclient:
            registration:
              client-id: chatClient
              client-secret: nosecret
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - ${app.web.oauth2.redirect}
              scopes:
                - auth
                - message
                - topic
                - user
                - openId
            require-authorization-consent: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
