spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserver
    driver-class-name: org.postgresql.Driver
  application:
    name: chat-authorization-server
  main:
    web-application-type: servlet
  security:
    oauth2:
      authorizationserver:
        client:
          chat-client:
            require-authorization-consent: true
            registration:
              client-id: chatClient
              client-secret: "{noop}nosecret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://authserv:9001/login/oauth2/code/chatClient
              scopes:
                - auth
                - message
                - topic
                - user
                - openId

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO