server:
  port: 9000
spring:
  application:
    name: chat-authorization-server
  main:
    web-application-type: servlet

app:
  primary: auth
  proto: rsocket
  key:
    type: long

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE