server:
  port: 6702

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
spring:
  main:
    web-application-type: reactive
    application:
      name: chat-gateway
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://authserv:9000
        registration:
          spring:
            provider: spring
          client-id: chatClient
          client-secret: nosecret
          authorization-grant-type: authorization_code
          client-authentication-method: client_secret_basic
          redirect-uri: http://authserv:9000/login/oauth2/code/{registrationId}
          scope:
            - user
            - topic
            - message
            - openId
  cloud:
    gateway:
      routes:
          - id: global
            uri: http://core-service-http:6792
            predicates:
              - Path=/**