server:
  port: 6702

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  main:
    web-application-type: reactive
    application:
      name: chat-gateway
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
        registration:
          spring:
            provider: spring
            client-id:
            client-secret:
            authorization-grant-type:
            client-authentication-method:
            redirect-uri:
            scope: