apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-chat
spec:
  template:
    spec:
      containers:
      - name: memory-core-service-rsocket
        envFrom:
          - secretRef:
              name: chat-server-keystore-pass
        volumeMounts:
        - mountPath: /etc/keys
          name: chat-certs
          readOnly: true
