server:
port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

org:
  springframework:
    web:
      reactive:
        result:
          view:
            RedirectView: TRACE
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.oauth2.issuerUri:http://authserv:8080}


users:
  base-uri: http://127.0.0.1:6702/chat/users